In [1]:
import numpy as np


NumPy arrays

In [3]:
one_d_array = np.array([1, 2, 3])

print(one_d_array)

[1 2 3]


In [5]:
two_d_array = np.array([[1, 2], [3, 4]])
print (two_d_array)

[[1 2]
 [3 4]]


NumPy Array Attributes

In [13]:
print(one_d_array.shape)
print(one_d_array.size)
print(one_d_array.dtype)
print(one_d_array.itemsize)

(3,)
3
int64
8


In [ ]:
#Check palindrome

In [17]:
an_array = np.array([1, 2, 3, 4])
reshaped_array = an_array.reshape(2, 2)

print(reshaped_array)

[[1 2]
 [3 4]]
